//
//  ExampleEntity.m
//
//  Generated by wadl2objc 8/27/13.
//  XSD v.1.0

//  DO NOT MODIFY THIS CLASS

#import <Foundation/Foundation.h>
#import "BaseEntity.h"
#import "XSDSimpleTypes.h"

@interface _ProductItem : BaseEntity

@property(nonatomic, strong) NSNumber *defaultQuantity
@property(nonatomic, strong) NSString *division
@property(nonatomic, strong) NSArraygarmentTypes
@property(nonatomic, strong) NSNumber *id
@property(nonatomic, strong) NSString *itemDescription
@property(nonatomic, strong) NSString *itemId
@property(nonatomic, strong) NSNumber *retailPrice

@end
