//
//  ExampleEntity.m
//
//  Generated by wadl2objc 8/27/13.
//  XSD v.1.0

//  DO NOT MODIFY THIS CLASS

#import <Foundation/Foundation.h>
#import "BaseEntity.h"
#import "XSDSimpleTypes.h"

@interface _Role : BaseEntity

@property(nonatomic, strong) NSNumber *id
@property(nonatomic, strong) NSString *roleName
@property(nonatomic, strong) RoleTypetype

@end
