//
//  ExampleEntity.m
//
//  Generated by wadl2objc 8/27/13.
//  XSD v.1.0

//  DO NOT MODIFY THIS CLASS

#import <Foundation/Foundation.h>
#import "BaseEntity.h"

@interface _TailorPerformanceInfo : BaseEntity

@property(nonatomic, strong) NSNumber *allocated
@property(nonatomic, strong) NSNumber *archived
@property(nonatomic, strong) NSString *uniqueId

@end
